server:
  port: 8761

spring:
  application:
    name: service-registry

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/



